### ISSUE TITLE
Unable to reach radiative-convective equilibrium at the top of the atmosphere

### ISSUE THREAD

**Issue by HaynesStephens** [CliMT/climt#105]
* CliMT version: 0.16.3
* Python version: 3.5.2
* Operating System: MacOS

### Description

I am trying to run a single-column model and have it reach radiative-convective equilibrium. For some reason, the top of the atmosphere doesn't reach equilibrium (zero net flux) before the simulation seems to go crazy and experience drastic distinct changes with no sign of approaching a steady state. 

### What I Did

I've ran two kinds of simulations.
The first uses the following climt imports:
- EmanuelConvection, RRTMGShortwave, RRTMGLongwave, SlabSurface, SimplePhysics, get_default_state
The second uses the same imports with one additional import:
- DryConvectiveAdjustment

In both cases, I have used to slab ocean surface with a mixed layer depth of 0.01 meters and surface albedos of 0.06. I have tried two different uniform molar fractions of carbon dioxide in the atmosphere (0.00027 and 0.00033). 

I've used a time step of 10 minutes, running the simulations for about 450 days each.
Attached are the Python scripts that I've been using (in the form of txt files).

### Any advice on how to get the simulation to reach an equilibrium state? 
Please let me know.

[dry_convection_adjustment.txt](https://github.com/CliMT/climt/files/3214456/dry_convection_adjustment.txt)
[moist_convection.txt](https://github.com/CliMT/climt/files/3214457/moist_convection.txt)

**Comment by JoyMonteiro** [comment]
Hi,

I have found single column models always tricky to work with, since they cannot export excess energy. Especially in the presence of moisture, SCMs tend to run away (there is a positive feedback between longwave heating and moisture content in the atmosphere).

I have a feeling the much lower albedo is causing the SCM to run away. Could you check to see
if the surface temperature continues to rise throughout the simulation? I don't have time until late
next week to run these scripts myself, but hopefully can help you diagnose the issue.

**Comment by HaynesStephens** [comment]
Hey Joy,

I checked and yes, the surface temperature does continue to rise throughout the simulation. Is there a way to include some realistic shedding of energy from the column, or is it possibly unable to reach equilibrium given the albedo and CO2 levels? The reason I used an albedo of 0.06 is because I am trying to simulate the open ocean as my surface.

**Comment by JoyMonteiro** [comment]
AFAIK, there is no "standard" way to do this. A simple way would be to use 
an additional cooling term, but where and how much to cool is not obvious.

A ConstantTendencyComponent or RelaxationTendencyComponent from sympl
https://github.com/mcgibbon/sympl/blob/master/sympl/_components/basic.py

should allow you to implement such a cooling term.

I have always kept SCM integrations stable by changing the zenith
angle used by the shortwave radiation. With some trials, you should
be able to find a value which keeps it stable. It will likely be close
to the pole.

**Comment by JoyMonteiro** [comment]
I'm closing this issue, feel free to reopen if it is still relevant!
