### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by zylkowski** [CliMT/climt#125]
* CliMT version: 0.16.9
* Python version: 3.6/3.7/2.7
* Operating System: Windows 10

### Description

I just installed CliMT with intention to make project for university classes. I wanted to make simple climate model and simulate it.
After installation and creating simple model I get multiple `DLL load failed: The specified module could not be found.` errors from CliMT. I installed it through pip(like in docs) on all mentioned versions of Python without success.

**Comment by JoyMonteiro** [comment]
Thanks for the report, I will try to see what is happening. It might take some time for me to investigate this issue. In the meantime, could you see if an earlier version successfully installs?

I must mention that I have also successfully used Google Colab to run climt models during courses where students had issues installing climt on windows. If you would like to try out this option, let me know, I can setup a simple model as an illustration.

**Comment by zylkowski** [comment]
Thank you very much for looking into it. Also thanks for mentioning Google Colab, everything seems to be working fine except for some sympl error. Thank you again!

**Comment by JoyMonteiro** [comment]
Great, glad this worked out! Windows builds seem to work on some machines and not others and it
is hard to replicate the error.

I'll close this issue and open another one to keep track of the Windows problem.
