### ISSUE TITLE
Diagnosing the contributions of each component in the model

### ISSUE THREAD

**Issue by edenau** [CliMT/climt#126]
* CliMT version: 0.16.9
* Python version: 3.7
* Operating System: Linux

### What I did

I'm constructing a climt model with components such as convection and radiation using the code below:
```
convection = climt.EmanuelConvection()
simple_physics = sympl.TimeDifferencingWrapper(climt.SimplePhysics())
radiation = climt.GrayLongwaveRadiation()
climt.GFSDynamicalCore([simple_physics, radiation, convection], number_of_damped_levels=5)
```

I know I can increment the model by one timestep using the following code:
```
diagnostics, new_state = dycore(state, timestep)
state.update(diagnostics)
state.update(new_state)
state['time'] += timestep
```

### Description

I would like to diagnose the contributions of each component (i.e. convection, physics, radiation) to the states. Is there any trivial way to do so? Thanks!

**Comment by JoyMonteiro** [comment]
Hello Eden,

All sympl components can be initialised with a flag which will copy tedencies generated by them to diagnostics.
just set the `tendencies_in_diagnostics` flag to `True` during component creation.

https://github.com/mcgibbon/sympl/blob/f97e21153c27e1659612699fd717be093ff106d6/sympl/_core/base_components.py#L688

Hope this is what you were looking for.

**Comment by edenau** [comment]
That works, thanks!
