### ISSUE TITLE
Windows builds fail on some systems.

### ISSUE THREAD

**Issue by JoyMonteiro** [CliMT/climt#127]
* CliMT version: 0.16.9
* Python version: all versions
* Operating System: Windows 10

Check if we can reproduce this

**Comment by zylkowski** [comment]
I actually replicated it on 6 different computers, one of which had Linux.

**Comment by JoyMonteiro** [comment]
Oh, that is definitely not good since climt is used most extensively on Linux/Mac.

Could you please let me know the specs of the Linux computer where the build failed?
Does this issue persist if you install the previous version of climt?

**Comment by zylkowski** [comment]
Ubuntu 20.04, python 3.8.1. Unfortunately I can't check now if previous versions of climt work fine there.

**Comment by JoyMonteiro** [comment]
Ah, that makes sense. We haven't yet created wheels for py38. I'll get that done right away. Thanks for the information!

**Comment by JoyMonteiro** [comment]
py38 wheels for Linux have been released, please `pip install -U climt` to get them.
