### ISSUE TITLE
No default state for Ice sheet component

### ISSUE THREAD

**Issue by zylkowski** [CliMT/climt#128]
* CliMT version: 0.16.9
* Python version: 3.6.9
* Operating System: Google Colab/Linux

### Description

I am trying to `get_default_state()` for `IceSheet` component but there doesn't seem to be one which enables me to for example simulate Earth. I don't know if it is considered issue but nonetheless I would appreciate help considering simulating Earth with realistic IceSheet component starting values.

**Comment by JoyMonteiro** [comment]
@zylkowski sorry for the delayed reply, I'm travelling currently. 

The default state for `IceSheet` is no ice, which is not realistic for Earth, as you mentioned.

climt is not full featured enough to get a realistic Earth climate -- it cannot handle topography (especially the gravity wave drag), cloud microphysics, and some other processes essential for a realistic climate. It is meant to be used for more idealised modelling where such limitations are not an issue.

If you let me know what your use case is, I might be able to suggest something more.

**Comment by zylkowski** [comment]
@JoyMonteiro no problem. 

I have a couple of rookie questions which don't really fit in github issues tab. Can I email you with those? I would really apprecieate help.

**Comment by JoyMonteiro** [comment]
Absolutely. You'll find an email address here:
http://www.iiserpune.ac.in/people/faculty-details/200

**Comment by JoyMonteiro** [comment]
Closing this for now.
