### ISSUE TITLE
pip install fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by atantet** [CliMT/climt#129]
* CliMT version: 0.16.9
* Python version: 3.8.6
* Operating System: Ubuntu 18.04

### Description

Install fails with pip : `cp: '../lib/libopenblas.a': No such file or directory`

Note that build appears to fail on PyPI as well : https://pypi.org/project/climt/

My full log : 

[install_climt.txt](https://github.com/CliMT/climt/files/5887864/install_climt.txt)

### What I Did

```
pip install climt
```

**Comment by JoyMonteiro** [comment]
This is a known issue, that we have still not updated our CI to build py38/39 wheels for any system. I have a few other deadlines to meet, so this won't happen in the next few weeks.

In the meantime, a workaround could be to create a virtual environment with py36/37, for which wheels are available on PYPI.

Could you please check if that works?

**Comment by atantet** [comment]
Thanks for the very quick reply.

It indeed works in a new environment with python==3.7

I am testing it to run on a JupyterLab with py38 so I will not be able to use it in the near future but I am looking forward to. Thanks !

**Comment by JoyMonteiro** [comment]
Oh, I see. I'll keep this issue open and if let you know if I can manage to build climt over the weekend.

**Comment by JoyMonteiro** [comment]
We finally released linux wheels for py38. Please `pip install -U climt` to get it.

**Comment by guidoca** [comment]
Hi. I had a similar issue with py39. I skipped the issue by installing from source and downloading a more recent version of OpenBLAS-0.3.17. Even though installation worked it seems to get some errors on the tests, mostly some NameError (name 'phys' is not defined, and others for _rrtmg_sw, _emanuel_convection, _gfs_dy...), so i have to be missing something..

Are there linux wheels for py39?

**Comment by JoyMonteiro** [comment]
Sorry, not yet! Did you happen to follow the instructions on readthedocs for installing from source? There are some preparatory variable setting etc., that ensures a clean build.
