### ISSUE TITLE
import climt gives an error

### ISSUE THREAD

**Issue by Ai33L** [CliMT/climt#141]
* CliMT version: 0.16.9
* Python version: 3.8.5
* Operating System:

### Description

running import climt does not work and errors out.

the error output saved to file:
[log.txt](https://github.com/CliMT/climt/files/6359252/log.txt)

### What I Did

Ran a python code with "import climt" as the only command.

**Comment by JoyMonteiro** [comment]
What operating system are you working with? On linux we have a released a newer version of climt (0.16.14) just today.

**Comment by JoyMonteiro** [comment]
I have just verified that climt does work on py38, but with the latest numpy (1.20.2). `import climt` failed with exactly the same error on an older version (1.19.x)

**Comment by JoyMonteiro** [comment]
closing this as it seems to be a numpy version issue, and not a climt issue.
