### ISSUE TITLE
Python3  gmd_aquaplanet.py produces error in Linux

### ISSUE THREAD

**Issue by oculus99** [CliMT/climt#156]
* CliMT version:current 
* Python version: 3.10
* Operating System:climt 0.16.25

### Description
/usr/local/lib/python3.8/dist-packages/sympl/_core/dataarray.py:6: FutureWarning: xarray subclass DataArray should explicitly define __slots__
  class DataArray(xr.DataArray):
Traceback (most recent call last):
  File "gmd_aquaplanet.py", line 94, in <module>
    diag, my_state = dycore(my_state, model_time_step)
  File "/usr/local/lib/python3.8/dist-packages/climt/_components/gfs/component.py", line 311, in __call__
    raw_state['tracers'] = self._tracer_packer.pack(state)
  File "/usr/local/lib/python3.8/dist-packages/sympl/_core/tracers.py", line 202, in pack
    array[tracer_slice] = raw_state[name]

### What I Did

python3 gmd_aquaplanet.py

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by JoyMonteiro** [comment]
Thanks for raising this issue. As of now, there are no binary builds for Python 3.10 (should be released sometime soon).

Until then, please use a virtual environment with python 3.8/3.6. I suspect things should work then.

Also, it does not look as if your traceback is complete. Please post a full traceback to ensure we can actually see the issue.

I'm closing this issue now, feel free to reopen if your problem persists.
