### ISSUE TITLE
Provide binary wheels for Python 3.9+

### ISSUE THREAD

**Issue by lkluft** [CliMT/climt#158]
Dear CliMT developers,

thanks for the great work with this package!

Our package konrad is still heavily relying on your nice RRTMG python interface. Unfortunately, we noticed that the installation became more troublesome lately, because the pre-built binary wheels for CliMT only support `python<=3.8`. Lately, a lot of HPC clusters (and GitHubs CI) provide more recent Python versions, which forces the user to compile the whole stack of FORTRAN libraries.

Would it be possible to provide binary wheels for more recent Python versions or does this cause problems with some of your dependencies?

**Comment by JoyMonteiro** [comment]
Hello Lukas,

yes, we are actively working to fix this. There are some CI and openblas
related issues that we needed to figure out. We now know how to fix them,
but other work is slowing this down. Are you mainly looking for the single
column stuff, or are you using the dycore as well?

Joy

**Comment by lkluft** [comment]
Hey Joy,

for our package, we only need the RRTMG interface. We came up with our own _poor man's_ versions of the single column stuff relevant to us :-)

Let me know if I there is anything to help without an in-depth knowledge of CliMT.

Cheers
Lukas

**Comment by JoyMonteiro** [comment]
Thanks to @Ai33L, I have just released wheels for 3.7-3.9, without the dynamical core, but everything else. Could you please check and see if konrad works fine with this. I will be updating this again with 3.10

**Comment by lkluft** [comment]
Thanks for the release! It does work perfectly fine on Linux! :-)

On MacOS, the binary wheel is not used, but this is likely due to different architectures (I use an M1 MacBook).

**Comment by JoyMonteiro** [comment]
Great! Yes, the mac wheels are unlikely to run on M1. I don't have access
to that
hardware to build or test. Hopefully once Github introduces M1 hardware this
will no longer be an issue.

Joy

**Comment by lkluft** [comment]
Yes, I thought so. The M1 wheels are an issue that is most likely affecting lots of packages on not only CliMT -- I think it is fine to leave it until Github comes to save the day.

The Linux wheels look nice, though 👍 So I think you can try 3.10 (if that's straight-forward).

**Comment by JoyMonteiro** [comment]
py310 wheels also up! If it all looks good, then I'll close this issue.

**Comment by lkluft** [comment]
The binary wheels for 3.10 also work 👍  I also checked the MacOS wheels through our Github Actions and the tests run through as well. I think the issue can be closed :)

Thanks a lot for the quick fix! 🚀
