### ISSUE TITLE
Outdated docs?

### ISSUE THREAD

**Issue by nbren12** [CliMT/climt#20]
The [docs](https://climt.readthedocs.io/en/latest/generated/climt.EmanuelConvection.html#climt.EmanuelConvection) seem to be outdated for EmanuelConvection. No idea why, if you're using autodoc.

**Comment by nbren12** [comment]
BTW, @mcgibbon was the one who made this issue w/ while sitting at my computer. I'm going to unsubscribe.

**Comment by JoyMonteiro** [comment]
@mcgibbon  readthedocs only builds when master is updated. I guess we should change that behaviour.

**Comment by JoyMonteiro** [comment]
Fixed.
