### ISSUE TITLE
Ozone profile data missing

### ISSUE THREAD

**Issue by Strong-Curious** [CliMT/climt#22]
* CliMT version: Latest
* Python version: 3
* Operating System: Colaboratory

### Description

Trying to load the default state, but the file is missing

### What I Did

```
 state = get_default_state([simple_physics, convection,
                                 radiation_lw, radiation_sw, slab])
```

Error:
```
  No such file or directory: '/usr/local/lib/python3.6/dist-packages/climt/_data/ozone_profile.npy  
```

**Comment by Strong-Curious** [comment]
I'm trying to use Google Colaborator for using CliMT, and I can't clone it remotely. Is there any chance that the pip install command will download the file to the right place?

Thank you

**Comment by mcgibbon** [comment]
There are currently no files in the _data directory of the [pypi distribution of CliMT](https://pypi.python.org/pypi/climt/0.9.1). I'm guessing they should be there.

**Comment by JoyMonteiro** [comment]
Oh, I see. sucks that the release has this issue, but a new release will be out by the end of the month.

In the meantime, if you can pip install, that means you have write permissions on that folder. could you just copy the file from the link above after you install?

**Comment by JoyMonteiro** [comment]
There are some bug fixes and enhancements to the RRTMG wrapper since that release. I suggest you keep a watch out and upgrade as soon as the new release is out.

**Comment by mcgibbon** [comment]
You can use pip to install directly from GitHub. I think the following line should work:

`pip install git+git://github.com/CliMT/climt.git#egg=climt`

This may not install dependencies, so you may need to install those manually (using pip) when using pip to install the git repository

**Comment by mcgibbon** [comment]
If you would like to install from the last tagged package version, you would do 

`pip install git+git://github.com/CliMT/climt.git@v0.9.1#egg=climt`

**Comment by JoyMonteiro** [comment]
Thanks, @mcgibbon!

**Comment by JoyMonteiro** [comment]
@Strong-Curious , using the @v0.9.1 tag in the URL installs the version that does not have the ozone file. Using the previous URL that @mcgibbon showed should install the latest version.

http://codeinthehole.com/tips/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/

**Comment by Strong-Curious** [comment]
When I run:
```
pip install git+git://github.com/CliMT/climt.git#egg=climt
```

I get:
```
Requirement already satisfied: climt from git+git://github.com/CliMT/climt.git#egg=climt in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: cython>=0.25 in /usr/local/lib/python3.6/dist-packages (from climt)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.6/dist-packages (from climt)
Requirement already satisfied: pint>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from climt)
Requirement already satisfied: sympl>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from climt)
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.6/dist-packages (from climt)
Requirement already satisfied: xarray>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from climt)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from sympl>=0.2.1->climt)
Requirement already satisfied: pandas>=0.18.0 in /usr/local/lib/python3.6/dist-packages (from xarray>=0.8.0->climt)
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18.0->xarray>=0.8.0->climt)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18.0->xarray>=0.8.0->climt)
```

**Comment by JoyMonteiro** [comment]
How about either of
```
pip install -I git+git://github.com/CliMT/climt.git#egg=climt
pip install --ignore-installed git+git://github.com/CliMT/climt.git#egg=climt
```

**Comment by mcgibbon** [comment]
@JoyMonteiro, the v0.9.1 tag [does have the ozone file](https://github.com/CliMT/climt/tree/v0.9.1/climt/_data). Something went wrong when you uploaded the dist.

If it's saying it's already installed, you could first do `pip uninstall climt`.

**Comment by JoyMonteiro** [comment]
@mcgibbon, yes, I recall that the manifest file climt/MANIFEST.in was incorrect. So, sdist did not pull all the required files during upload.

**Comment by mcgibbon** [comment]
Good that you've identified and fixed the problem for future releases :)

**Comment by JoyMonteiro** [comment]
@Strong-Curious, I tested installing climt on the colaboratory. You will need the following commands
to get it to work:

```
pip install git+git://github.com/CliMT/climt.git@develop#egg=climt

pip install git+git://github.com/mcgibbon/sympl.git#egg=sympl

```
You will need them to run in this order. The new version of climt
requires some code that only exists in the github version of sympl.

**Comment by Strong-Curious** [comment]
Thank you very much !! !! !!

**Comment by JoyMonteiro** [comment]
Welcome :)
