### ISSUE TITLE
Using CliMT for correlation between convection and CO2

### ISSUE THREAD

**Issue by Ron7TAU** [CliMT/climt#24]
* CliMT version: Latest
* Python version: 3
* Operating System: Unbutu on Virtual Machine

### Description

I am trying to use CliMT in order to see how the SST and CO2 effect atmospheric convection. 
I've tried using your slab example from GitHub with some CO2 changes and SST forcing inside the loop - but I get no change in the convection heating rate, and numerical blowup after ~150 iterations (after debugging I saw that it might be because there is one value of temperature on ~500mb that is decreasing faster then the rest of the column).

Any Ideas what is wrong? 
Or any suggestions on how to see the convection and its relation to CO2 and SST in CliMT?

### What I Did

```
from sympl import (
    DataArray, AdamsBashforth, PlotFunctionMonitor, RelaxationPrognostic)
from climt import RRTMGShortwave, RRTMGLongwave, get_default_state, EmanuelConvection, SlabSurface, SimplePhysics
import numpy as np
from datetime import timedelta
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import math

%matplotlib notebook


def plot_function(fig, state):
    ax = fig.add_subplot(2, 2, 1)
    ax.plot(
        state['convective_heating_rate'].to_units('degK day^-1').values.flatten(),
        state['air_pressure'].to_units('mbar').values.flatten(), '-o')
    ax.set_title('Conv. heating rate')
    ax.set_xlabel('K/day')
    ax.set_ylabel('millibar')
    ax.grid()

    ax.axes.invert_yaxis()
    ax = fig.add_subplot(2, 2, 2)
    ax.plot(
        state['air_temperature'].values.flatten(),
        state['air_pressure'].to_units('mbar').values.flatten(), '-o')
    ax.set_title('Air temperature')
    ax.axes.invert_yaxis()
    ax.set_xlabel('K')
    ax.grid()

    ax = fig.add_subplot(2, 2, 3)
    ax.plot(
        state['longwave_heating_rate'].values.flatten(),
        state['air_pressure'].to_units('mbar').values.flatten(), '-o',
        label='LW')
    ax.plot(
        state['shortwave_heating_rate'].values.flatten(),
        state['air_pressure'].to_units('mbar').values.flatten(), '-o',
        label='SW')
    ax.set_title('LW and SW Heating rates')
    ax.legend()
    ax.axes.invert_yaxis()
    ax.set_xlabel('K/day')
    ax.grid()
    ax.set_ylabel('millibar')

    ax = fig.add_subplot(2, 2, 4)
    net_flux = (state['upwelling_longwave_flux_in_air'] +
                state['upwelling_shortwave_flux_in_air'] -
                state['downwelling_longwave_flux_in_air'] -
                state['downwelling_shortwave_flux_in_air'])
    ax.plot(
        net_flux.values.flatten(),
        state['air_pressure_on_interface_levels'].to_units('mbar').values.flatten(), '-o')
    ax.set_title('Net Flux')
    ax.axes.invert_yaxis()
    ax.set_xlabel('W/m^2')
    ax.grid()
    fig.tight_layout()

tp_profiles = np.load('thermodynamic_profiles.npz')
mol_profiles = np.load('molecule_profiles.npz')
air_temperature = tp_profiles['air_temperature']
air_temperature.shape


timestep = timedelta(minutes=5)

convection = EmanuelConvection()
radiation_sw = RRTMGShortwave()
radiation_lw = RRTMGLongwave()
slab = SlabSurface()

time_stepper = AdamsBashforth([convection, radiation_lw, radiation_sw, slab])

convection.current_time_step = timestep

mids = 60

mid_levels = {'label': 'mid_level',
              'values': np.arange(mids),
              'units': ''}

int_levels = {'label': 'interface_level',
              'values': np.arange(mids + 1),
              'units': ''}



# --- Getting THe Default State from CliMT ---- #

state = get_default_state([convection,
                           radiation_lw, radiation_sw, slab],mid_levels=mid_levels, interface_levels=int_levels)


# ---- Air Temperature & SST ----- #

state['air_temperature'].values[:] = 270


# ---- Specific Humidity ---- #

state['specific_humidity'].loc[dict(mid_levels=slice(0, 10))] = 0.015
state['specific_humidity'].loc[dict(mid_levels=slice(10, 30))] = 0.01

#----- CO2 Profiles ---- #

CO2 = mol_profiles['carbon_dioxide']   #Realistic CO2 Profile


# ------ ALbedo, Zenith & Others --- #

state['zenith_angle'].values[:] = np.pi/4
state['surface_temperature'].values[:] = 300.
state['ocean_mixed_layer_thickness'].values[:] = 50
state['area_type'].values[:] = 'sea'
state['surface_albedo_for_direct_shortwave'].values[:] = 0.5
state['surface_albedo_for_direct_near_infrared'].values[:] = 0.5
state['surface_albedo_for_diffuse_shortwave'].values[:] = 0.5



# ----------------------- #
# ---- Looping Again ---- #
# ----------------------- #

monitor = PlotFunctionMonitor(plot_function)

frames = 300

xt = np.zeros( (frames,mids) )
yt = np.zeros( (frames,mids) )
convt = np.zeros( (frames,mids) )

for i in range(frames):
    if i%27 == 0 :
        print(i)
    convection.current_time_step = timestep
    diagnostics, new_state = time_stepper(state, timestep)
    state.update(diagnostics)
    if i % 20 == 0:
        monitor.store(state)
    state.update(new_state)
    state['eastward_wind'].values[:] = 2.
    state['surface_temperature'].values[:] = 280.  # Forcing SST
    
    xt[i,:] = state['air_temperature']
    yt[i,:] = state['air_pressure'].to_units('mbar')
    convt[i,:] = state['convective_heating_rate'].to_units('degK hour^-1')    
```

**Comment by mcgibbon** [comment]
Could you link to the slab example you're referring to, and point out exactly what changes you made? This is a lot of code, and it may make it easier to debug.

**Comment by JoyMonteiro** [comment]
@mcgibbon, this issue is in response to an email Ron sent me today -- I asked him to raise an issue. I should be able to take it forward without additional input from him.

**Comment by JoyMonteiro** [comment]
@Ron7TAU, using a column model without a boundary layer almost always will crash. The boundary layer is required to keep the model stable by diffusing heat from the lower layers upwards.

Apart from this, I recommend a few change to your code:
* It is reasonable to assume CO2 is well mixed. You can simply use a constant value of CO2 to begin with.
* If you want a constant surface temperature, the best way is to simply remove the slab surface component from the model. Then, the model does not have `surface_temperature` as a prognostic variable, and so it will remain fixed.
* Use a larger value of `eastward_wind` so that equilibrium is reached faster.
* Use lesser vertical levels so that equilibrium is reached faster. Of course, this is a choice that is set by the scientific objective, not convenience.

I have modified your script, and this 
https://gist.github.com/JoyMonteiro/85038e1590cc7f06f69d0f393a92d4fe
seems to run without crashing. You can modify it to suit your requirements.

You can change CO2 like the following:
```python
state['mole_fraction_of_carbon_dioxide_in_air'].values[:] = 0.00033
```
for 330 ppm, for example. Similarly, you can modify SST:
```python
state['surface_temperature'].values[:] = 295.
```

Remember that this value of `surface_temperature` will be a constant throughout the
simulation.

**Comment by Ron7TAU** [comment]
Thank you very much! I will definitely check this code.

Several questions though:

1) What is the difference between the simple physics boundary layer and the Emanuel convection simulate_boundary_layer option? 

2) Is there any recommendation regarding the specific humidity?

**Comment by JoyMonteiro** [comment]
1. I don't recommend using the `simulate_boundary_layer` option. Then only reason it is present is to expose all functionality available in the emanuel fortran code. It modifies arrays in-place, and this generally makes it hard to keep track of what is happening. The simple physics package boundary layer code is a simple diffusive boundary layer scheme, and using it keeps the boundary layer and convection components separate.

2. I'm not sure what you expect from the humidity profiles. If you want to specify a humidity profile that triggers convection, you have to calculate the convective available potential energy (CAPE) for the given profiles of temperature and humidity. If this is positive, the emanuel scheme should kick in to remove the CAPE and stabilise the column. IMO, it is simply better to let the boundary layer scheme take care of this, unless you have a very specific profile (like something from an observational campaign) that you want to
use.

**Comment by JoyMonteiro** [comment]
@Ron7TAU  Closing for now, please reopen if needed.
