### ISSUE TITLE
pip install fails on older Cython

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#25]
* CliMT version: 0.9.1
* Python version: 2.7.13
* Operating System: CentOS

### Description

pip install fails when using Cython 0.23. Updating to Cython 0.27.3 fixed this issue. Should probably require a newer version of Cython (I don't know how new).

### What I Did
```
[mcgibbon@stcu python]$ pip install climt
Collecting climt
  Downloading climt-0.9.1.tar.gz (20.9MB)
    100% |████████████████████████████████| 20.9MB 20kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-djV6KO/climt/setup.py", line 5, in <module>
        from Cython.Build.Distutils import build_ext as native_build_ext
    ImportError: No module named Distutils

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-djV6KO/climt/
```

**Comment by JoyMonteiro** [comment]
Yes, this issue has been fixed in the repo. The setup script tries to
import cython and numpy, and if it does not find the correct versions,
installs them.

any version of cython >= 0.25 works.
