### ISSUE TITLE
pip install can't find required libraries

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#26]
* CliMT version: 0.9.1
* Python version: 2.7.13
* Operating System: CentOS

### Description

Trying to pip install CliMT. Got some GCC errors, particularly the following:

```
    gcc: error: /tmp/pip-build-k_D69F/climt/climt/_lib/Linux//libgfs_dycore.a: No such file or directory
    gcc: error: /tmp/pip-build-k_D69F/climt/climt/_lib/Linux//libshtns_omp.a: No such file or directory
    gcc: error: /tmp/pip-build-k_D69F/climt/climt/_lib/Linux//libfftw3_omp.a: No such file or directory
    gcc: error: /tmp/pip-build-k_D69F/climt/climt/_lib/Linux//libfftw3.a: No such file or directory
    gcc: error: /tmp/pip-build-k_D69F/climt/climt/_lib/Linux//libopenblas.a: No such file or directory
    error: command 'gcc' failed with exit status 1
```

Maybe there are files missing in the manifest? I'm attaching the full log from the pip install.

[log.txt](https://github.com/CliMT/climt/files/1734348/log.txt)

**Comment by JoyMonteiro** [comment]
According to the log, it failed to build fftw internally during build. Have you been successful in building from the repository on this machine? That should give me some more information to work with.

The log from building fftw and openblas should be present in a file called `log` within the respective folders in `climt/_lib/<fftw/openblas dir>`

**Comment by JoyMonteiro** [comment]
Has this issue been resolved?
