### ISSUE TITLE
Upgrading to sympl 0.4.0

### ISSUE THREAD

**Issue by JoyMonteiro** [CliMT/climt#29]
sympl 0.4.0 will bring a lot of changes which are incompatible with climt as it currently is. We will need to

* [ ] Change code so that 'x', 'y' wildcards are no longer used anywhere. This will require registering dimension names in `get_default_state()` which will be used to create the `*_properties` during run time.
* [ ] Get rid of all irrelevant code in `ArrayHandler`.
* [ ] Change all components to use the `array_call` interface
* [ ] New TimeSteppers won't work in convection schemes. Need to write new ones.

Not directly related, but desirable:
* [ ] If possible, figure out and move most memory allocation to 'c' format

I will keep updating this list as and when I figure out new requirements.

**Comment by mcgibbon** [comment]
Rather than registering dimension names, CliMT should just have names for its dimensions that are set by the dynamical core. Down the line if we get additional dynamical cores they might change, but for now there should in theory be only one possible set of horizontal dimensions.

**Comment by mcgibbon** [comment]
I would vote for "lat" and "lon".

**Comment by JoyMonteiro** [comment]
As of now, we allow the 'x', 'y', 'z' dimensions to have arbitrary names. I don't see any reason to make things more restrictive. Registering simply means we keep track of x,y,z which as passed into `get_default_state`, and using default ones (like "latitude", "longitude") if the state was created without the help of `get_default_state`.

**Comment by mcgibbon** [comment]
I have begun work on this in the sympl-0.4.0 branch.

**Comment by mcgibbon** [comment]
Fixed by #68
