### ISSUE TITLE
How to cite CliMT?

### ISSUE THREAD

**Issue by lkluft** [CliMT/climt#32]
Hey,

I have a more general issue absolutely unrelated to the code 😉 

We developed a simple climate model using the radiation part of CliMT. As we are about to publish first results I want to know if there is a preferred way to cite or at least acknowledge your work?

Cheers,
Lukas

**Comment by JoyMonteiro** [comment]
Your timing could not have been better ;)

The paper documenting sympl and climt was just put up for discussion:
https://www.geosci-model-dev-discuss.net/gmd-2018-100/

Also, it would be great if you let us know when your paper is published. We would like to add it to
our README to document users!

Joy

**Comment by lkluft** [comment]
Hey,

sorry I completely forgot to respond!

Thanks for pointing to the discussion paper, I will keep track of its status 👍 

Cheers,
Luaks
