### ISSUE TITLE
RRTMG extra dimension handling

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#40]
Two main points here:

- I may have found a bug, details below.
- The number of shortwave bands should be hard set by us somehow, since it is defined by a parameter in the Fortran code that can't be edited during runtime. This makes sense, if you consider that there's no way for us to configure what frequencies the shortwave bands correspond to.

In `rrtmg_sw_rad.f90`, the comments say the following:

    ! This call to RRTMG_SW must be preceeded by a call to the module
    !     mcica_subcol_gen_sw.f90 to run the McICA sub-column cloud generator,
    !     which will provide the cloud physical or cloud optical properties
    !     on the RRTMG quadrature point (ngptsw) dimension.

However, we never call mcica_subcol_gen_sw. That file produces all arrays that are meant to be of dimension `ngptsw`. Whatever we're doing is something quite weird.

For example, tracking cloud fraction, [at the component interface](https://github.com/CliMT/climt/blob/develop/climt/_components/rrtmg/sw/component.py#L424) we have `'cloud_area_fraction_in_atmosphere_layer'` which becomes `cloud_fraction` [in the cython wrapper](https://github.com/CliMT/climt/blob/develop/climt/_components/rrtmg/sw/_rrtmg_sw.pyx#L121), of dimension `[mid_levels, lat, lon]` at that point in Fortran ordering. That is [passed to](https://github.com/CliMT/climt/blob/develop/climt/_components/rrtmg/sw/_rrtmg_sw.pyx#L181) the parameter `cldfmcl` [in the Fortran code](https://github.com/CliMT/climt/blob/develop/climt/_components/rrtmg/sw/_rrtmg_sw.pyx#L121), which is [supposed to be of dimension `[ngptsw, ncol, nlay]`](https://github.com/CliMT/climt/blob/develop/climt/_components/rrtmg/sw/_rrtmg_sw.pyx#L333). We've told the Fortran code that ncol is 1 and nlay is the number of vertical levels, so we can pass a column at a time. So through this we pass in an array that doesn't even have a ngptsw dimension to the Fortran code that wants such a dimension. I feel like I'm missing something here, since that seems like the code shouldn't run at all.

I'll continue digging through this.

**Comment by mcgibbon** [comment]
@JoyMonteiro is it that we're actually using `rrtmg_sw_rad.nomcica.f90`? It seems like if that's the case, we're only allowed to use the "clear only" overlap method, and cloud fractions other than 0 and 1 aren't allowed. That would seem undesirable.

**Comment by mcgibbon** [comment]
OK for now I'll move forward with the Sympl 0.4.0 refactors leaving these as they are, but after that we should think about enabling MCICA. I may also add some code to make sure num_shortwave_bands is of the correct length.

**Comment by JoyMonteiro** [comment]
Closed by https://github.com/CliMT/climt/pull/83
