### ISSUE TITLE
logging instead of print

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#48]
CliMT should use the [built-in `logging` library](https://docs.python.org/2/library/logging.html) instead of `print` statements.

**Comment by JoyMonteiro** [comment]
I agree. I will keep this in mind for future development, and will get rid of any prints in the codebase in the coming months.

**Comment by mcgibbon** [comment]
I've already replaced most (all?) `print` statements in the `sympl-0.4.0` branch, but if you see any more you can replace them.

**Comment by JoyMonteiro** [comment]
This has been addressed, closing.
