### ISSUE TITLE
Possible bug in GFS tracer advection

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#51]
Lines 171-174 of phy_run_hs.f90:

    do trac=2,ntrac
        temp_grid_tracer(:,:) = dtracergdt(:,:,k,ntrac)
            call grdtospec(temp_grid_tracer, spectral_tracer_tend(:,k,ntrac))
    enddo

I suspect that the lines within this do loop should be referring to trac and not ntrac, so that they actually iterate over the tracers instead of repeatedly processing the final tracer?

**Comment by JoyMonteiro** [comment]
This has been fixed.
