### ISSUE TITLE
In GFS, set_model_grid should be the method to return grid variables

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#54]
Currently in the GFS pyx wrapper, `init_model` is what returns e.g. latitude and longitude grids, while `set_model_grid` is what actually generates those grids. Instead, `set_model_grid` should return those grids.

**Comment by JoyMonteiro** [comment]
perfectly fine by me.

**Comment by JoyMonteiro** [comment]
Made irrelevant by https://github.com/CliMT/climt/pull/68
