### ISSUE TITLE
Complex GFS case: tracers prognosed by contained Prognostic

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#55]
As we update GFS, we should ensure we solve the following case. A Prognostic may prognose some quantity X that is registered as a tracer with GFS. We need to ensure that its tendency is added to its corresponding entry in tracer tendencies in GFS.

**Comment by JoyMonteiro** [comment]
hmm, that's true. Once we have things working reliably, we could think of fixing this issue.

**Comment by mcgibbon** [comment]
I'm pretty much re-writing the wrapper interface to GFS at least at the Python level, so I'll make sure this case is handled as I write it. Just opened this issue so we can make sure that happened.

**Comment by JoyMonteiro** [comment]
Fixed by https://github.com/CliMT/climt/pull/68
