### ISSUE TITLE
Only update spectral arrays that have been modified

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#56]
In GFS, currently if any arrays have been modified then all spectral arrays will be re-generated. However, we only need to re-generate those spectral arrays whose physical counterpart has been modified.

**Comment by JoyMonteiro** [comment]
Yes, makes sense. of course, if you modify any wind field both vorticity and divergence must be updated. Since this part of the code is not expected to be called frequently in practice, I did not bother to optimise it.

**Comment by mcgibbon** [comment]
I'd expect it to be pretty frequent that someone might update humidity and temperature, for example, just at the surface in a surface flux scheme.

**Comment by JoyMonteiro** [comment]
sure, but that will have to be tested to work. Every spectral dycore based GCM that I have seen uses a finite difference version of implicit components like surface schemes.

**Comment by mcgibbon** [comment]
Ah, yeah you're right, surface schemes should be Prognostic and passed into the dycore.

**Comment by JoyMonteiro** [comment]
fixed by https://github.com/CliMT/climt/pull/68
