### ISSUE TITLE
Remove setphysicscallback from _gfs_dynamics.pyx

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#57]
`setPhysicsCallback(physicsFnPtr)` in [`_gfs_dynamics.pyx`](https://github.com/CliMT/climt/blob/develop/climt/_components/gfs/_gfs_dynamics.pyx#L73) doesn't seem to be called by its component. Should it be removed?

**Comment by JoyMonteiro** [comment]
yes please. This is a relic from the time when I was trying to call python subroutines from Fortran. It works, but I never used it.

**Comment by JoyMonteiro** [comment]
fixed by https://github.com/CliMT/climt/pull/68
