### ISSUE TITLE
Ensuring non-negativity of tracers for GFS

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#58]
Should GFS actually be the component to ensure that moisture and other tracers are non-negative, or should there be a component called after GFS which does so? For example, a user might have tracers which are okay to go negative, or might want to ensure global conservation of moisture. Currently the only way to modify this behavior is to modify GFS, but instead it could be that the user swaps out different components outside of the model. We could have a flag `make_tracers_nonnegative=False` (or `True`) on initialization if you like.

**Comment by JoyMonteiro** [comment]
I'm fine with the initialisation flag, but only for water vapour (something like `keep_water_vapour_positive=True`) which is `True` by default. Water vapour is required to be non-negative and is used by the dynamics as well. At this moment, I don't think GFS should worry about the sign of other tracers.

**Comment by mcgibbon** [comment]
Agreed. Though despite it being neither of our native spellings, I would use the American spelling for vapor to stay consistent.

**Comment by JoyMonteiro** [comment]
sounds good.

**Comment by JoyMonteiro** [comment]
fixed by https://github.com/CliMT/climt/pull/68
