### ISSUE TITLE
Require minimum horizontal dim size for GFS

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#59]
The GFS code will crash if the horizontal dimensions are not sufficiently large. I don't know exactly the minimum value, but it's more than 8 and less than or equal to 18. We should add checks to GFS that will raise informative exceptions if the minimum size is not met, to avoid a non-descriptive segmentation fault.

@JoyMonteiro do you know the minimum size?

**Comment by JoyMonteiro** [comment]
Nope, but I would restrict it to 36 latitudes, which corresponds to T12. This is kind of the lowest resolution that I have seen anyone run a dynamical core with.

**Comment by JoyMonteiro** [comment]
fixed by https://github.com/CliMT/climt/pull/68
