### ISSUE TITLE
Passing physical constants

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#6]
I've been wondering whether passing in physical constants on initialization to components is actually a good idea. Perhaps we should always use the constant included in `sympl.default_constants`? This would greatly simplify the docstrings and call signatures of components, and more effectively ensures consistent models.

If people really want to, they should be able to give components different values by having different ones in `default_constants` on initialization. We can accomplish this by storing the current value in self._constant_name on initialization, like we do already.

**Comment by JoyMonteiro** [comment]
fixed in new commit. Needed to add wrapper around constants handling, still under development.
