### ISSUE TITLE
Unit handling code is slow

### ISSUE THREAD

**Issue by mcgibbon** [CliMT/climt#75]
@JoyMonteiro brought up that currently when run in SCM mode, unit conversion checking takes up a significant amount of CliMT's runtime. We may want to add a faster backend for unit handling.

**Comment by JoyMonteiro** [comment]
I don't mind spending some time profiling different libraries. Which ones do you suggest?

Also, this library would need to be registered with `sympl`. Do you propose adding an API to
do this, or will it replace `pint` as a dependency?

**Comment by mcgibbon** [comment]
I'll need to write an internal backend API and wrappers for each library. This would technically make pint an optional dependency, but I'd say we should keep it as is to make sure there is at least one unit library installed, because it is pure Python with few dependencies of its own. We could default to cfunits when it is present.

**Comment by mcgibbon** [comment]
Let's move discussion over to an [issue](https://github.com/mcgibbon/sympl/issues/43) on Sympl.
