### ISSUE TITLE
Fix nomenclature

### ISSUE THREAD

**Issue by JoyMonteiro** [CliMT/climt#78]
All radiation components provide fluxes. `GrayLongwaveRadiation` currently uses the suffix `on_interface_levels` whereas `RRTMG*` do not.

One of the reasons to use that suffix was to distinguish between the same quantity on different levels.
To my knowledge, fluxes are always defined on interface levels, making the suffix redundant. This also
makes the label really unwieldy: `upwelling_longwave_flux_in_air_on_interface_levels` or `upwelling_longwave_flux_in_air_on_interface_levels_assuming_clear_sky` is really too long,
especially when it does not seem necessary.

I propose we do not use the suffix for these quantities. 

If in the future we include a radiation component which actually outputs fluxes on model levels, we could bring it back.

**Comment by mcgibbon** [comment]
I think this is reasonable. We could change our stance to be that a suffix is added for the less obvious level arrangement. For example, if we had radiative fluxes on mid levels, those would be called e.g. `upwelling_longwave_flux_in_air_on_mid_levels`. I would keep vertical wind naming as-is.

**Comment by JoyMonteiro** [comment]
I concur. This is fixed by https://github.com/CliMT/climt/pull/80
