### ISSUE TITLE
PressureFunctionDiagnosticComponent might need surface pressure

### ISSUE THREAD

**Issue by JoyMonteiro** [CliMT/climt#79]
`PressureFunctionDiagnosticComponent` is used for certain initialisations in climt. It is used to initialise longwave optical depth, but that function needs (rather should use) sigma values rather than pressure values.

Consequently, the values of longwave optical depth in the default state are off by 5 orders of magnitude.

I propose this component accept surface pressure by default, so that any such calculation can be
performed easily.

**Comment by mcgibbon** [comment]
This sounds reasonable to me. This component is used only internally, so it's fine for us to change its API.

**Comment by JoyMonteiro** [comment]
Fixed by https://github.com/CliMT/climt/pull/80
