### ISSUE TITLE
Installing Climt on MAC OSX Mojave

### ISSUE THREAD

**Issue by musdfakoc** [CliMT/climt#89]
* CliMT version: 0.15.3
* Python version: 2.7.15
* Operating System: OSX Mojave

### Description

I was trying to install the climt to python yet even though every site package has been installed when I try to install climt it gives error as "failed to build to wheel for climt".

I just try pip install climt

```
Failed building wheel for climt

Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ls/k_3dbdxn1g1fj46j0zg_dxnw0000gn/T/pip-install-moOkG1/climt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ls/k_3dbdxn1g1fj46j0zg_dxnw0000gn/T/pip-record-90TgDY/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ls/k_3dbdxn1g1fj46j0zg_dxnw0000gn/T/pip-install-moOkG1/climt/
```

**Comment by musdfakoc** [comment]
Thank you i installed with python 3.7 yet it did not work properly in that. when I followed the steps there it gives me this 
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ls/k_3dbdxn1g1fj46j0zg_dxnw0000gn/T/pip-install-KBu_Ti/climt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ls/k_3dbdxn1g1fj46j0zg_dxnw0000gn/T/pip-record-xyvi6R/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ls/k_3dbdxn1g1fj46j0zg_dxnw0000gn/T/pip-install-KBu_Ti/climt/

**Comment by JoyMonteiro** [comment]
Yes, unfortunately we do not yet have a 3.7 binary. `pip install climt` for Mac will _only_ work with Python 3.6. For any other version, you will have to use the build instructions that I mentioned above. It is unlikely `pip install climt` will succeed (though theoretically it should!).

did you try building it from source? it is not very hard if you have Anaconda and brew installed compilers.

**Comment by musdfakoc** [comment]
I also download the python3.6 and try to install climt. It did install yet it did not work properly for example it did not draw graphs.

**Comment by musdfakoc** [comment]
in python2 it cannot find "lib open blas" yet it is already installed on the mac

**Comment by JoyMonteiro** [comment]
we build our own libopenblas as part of the install process. This is done to ensure that we always
build against the same version of openblas and don't depend on external libraries. So, what you are seeing is that the openblas build failed, for whatever reason.

if you paste the full output you get from running `python setup.py install` from a source directory, we could maybe get an idea of what is happening. It is harder to debug a `pip install climt` in python 2.7 on Mac.

**Comment by musdfakoc** [comment]
now it is giving this

Traceback (most recent call last):
  File "/Users/mustafakoc/Downloads/climt-0.15.3/setup.py", line 32, in <module>
    with open('README.rst') as readme_file:
IOError: [Errno 2] No such file or directory: 'README.rst'

**Comment by JoyMonteiro** [comment]
hmm, ok. I think I should not have pointed you to the release tarball. Could you use this tarball instead?
https://github.com/CliMT/climt/archive/v0.15.3.tar.gz

**Comment by musdfakoc** [comment]
thanks yet it still says there is no readme.rst even it exists in the folder

**Comment by musdfakoc** [comment]
also it did not work in jupyter too it gives error

**Comment by JoyMonteiro** [comment]
> it still says there is no readme.rst even it exists in the folder

I think you will have to describe in details the steps you followed. I don't think I understand enough
about what you did.

> also it did not work in jupyter too it gives error

Again, I will need more details about the kind of error you get to be able to help...

**Comment by musdfakoc** [comment]
[climt.pdf](https://github.com/CliMT/climt/files/2454423/climt.pdf)
you wanna try it with teamviewer?

**Comment by JoyMonteiro** [comment]
let's keep teamviewer as a last resort. From your log, everything seems to be
built ok. Sucks that things are not working as expected. I will get back to you
about this in a bit.

Also, could you tell me what error the installed version gives? This is valuable information
since Mac builds have been an issue forever...

**Comment by musdfakoc** [comment]
Ok here is my new problem
I installed ubuntu with virtual desktop and set up everything there as written in the instructions on climt. When I run the examples in climt it says “Illegal instruction (core dumped)” do you somehow know why ? Thanks

**Comment by JoyMonteiro** [comment]
I really cannot say why such configurations will fail. It is impossible for me to ensure climt builds successfully on every possible combination of operating system/virtual machines!

 I suggest you wait for a day or two for me to get back on this since I'm about a release a new version of climt. Hopefully I will have a 3.7 binary wheel up and running as well.

> actually I believe still the problem is with the matplotlib since in python3 it installs and run the climt yet the graphics are not opening

does this mean you get graphics when you run these scripts in a jupyter notebook with the keyword `%matplotlib notebook` at the top of the cell?

**Comment by musdfakoc** [comment]
Nope unfortunately, in jupyter I still cannot get graphics.

**Comment by musdfakoc** [comment]
When I am on the computer I will send the errors on jupyter to you.

**Comment by JoyMonteiro** [comment]
Then how do you know climt is running?

For example, does this
```python
import climt
import numpy as np
from datetime import timedelta


model_time_step = timedelta(seconds=600)

grid = climt.get_grid(nx=128, ny=62)

held_suarez = climt.HeldSuarez()
dycore = climt.GFSDynamicalCore([held_suarez])
my_state = climt.get_default_state([dycore], grid_state=grid)

my_state['eastward_wind'].values[:] = np.random.randn(*my_state['eastward_wind'].shape)

for i in range(10000):
    diag, output = dycore(my_state, model_time_step)
    if (my_state['time'].hour % 2 == 0 and
            my_state['time'].minute == 0):
        print('max. zonal wind: ', np.amax(my_state['eastward_wind'].values))
    my_state.update(output)
    my_state['time'] += model_time_step
```

print something if you run it on the terminal?

**Comment by musdfakoc** [comment]
Yes it prints. the problem is with the matplotlib

**Comment by musdfakoc** [comment]
For instance the another code in examples i dont remember the name yet the one with prints temperature, it prints the temperatures on the screen yet does not show the graphs

**Comment by JoyMonteiro** [comment]
great, good to know! Will get back to you on the 3.7 issue asap.

**Comment by JoyMonteiro** [comment]
Great, that's exactly what I expected. So, climt is working.

Can you unzip and run this notebook and see if you get plots after a minute or so?

[HS_Test.ipynb.zip](https://github.com/CliMT/climt/files/2458683/HS_Test.ipynb.zip)

**Comment by musdfakoc** [comment]
It does not show me the plot it stays like that 
![screen shot 2018-10-09 at 12 47 45](https://user-images.githubusercontent.com/43886706/46662928-60ede780-cbc5-11e8-8847-06fb1d787513.png)

when I run it in the idle it says

Traceback (most recent call last):
  File "/Users/mustafakoc/Downloads/HS_Test.py", line 7, in <module>
    get_ipython().magic('matplotlib notebook')
NameError: name 'get_ipython' is not defined

**Comment by musdfakoc** [comment]
when I stop the jupyter it says

/Users/mustafakoc/anaconda3/lib/python3.7/site-packages/sympl/_core/tracers.py:202: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  array[tracer_slice] = raw_state[name]
max. zonal wind:  4.023865123812444
/Users/mustafakoc/anaconda3/lib/python3.7/site-packages/sympl/_core/tracers.py:229: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  raw_state[name] = tracer_array[tracer_slice]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in _get_axis_num(self, dim)
    135         try:
--> 136             return self.dims.index(dim)
    137         except ValueError:

ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-f246e5636c85> in <module>()
     41             my_state['time'].minute == 0):
     42         print('max. zonal wind: ', np.amax(my_state['eastward_wind'].values))
---> 43         monitor.store(my_state)
     44     my_state.update(output)
     45     my_state['time'] += model_time_step

~/anaconda3/lib/python3.7/site-packages/sympl/_components/plot.py in store(self, state)
     68             fig = plt.figure()
     69 
---> 70         self._plot_function(fig, copy_state(state))
     71 
     72         fig.canvas.draw()

<ipython-input-2-f246e5636c85> in plot_function(fig, state)
     13 
     14     ax = fig.add_subplot(1, 2, 1)
---> 15     state['air_temperature'].mean(dim='lon').plot.contourf(
     16         ax=ax, levels=16)
     17     ax.set_title('Temperature')

~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in wrapped_func(self, dim, axis, skipna, keep_attrs, **kwargs)
     21                              keep_attrs=False, **kwargs):
     22                 return self.reduce(func, dim, axis, keep_attrs=keep_attrs,
---> 23                                    skipna=skipna, allow_lazy=True, **kwargs)
     24         else:
     25             def wrapped_func(self, dim=None, axis=None, keep_attrs=False,

~/anaconda3/lib/python3.7/site-packages/xarray/core/dataarray.py in reduce(self, func, dim, axis, keep_attrs, **kwargs)
   1589             summarized data and the indicated dimension(s) removed.
   1590         """
-> 1591         var = self.variable.reduce(func, dim, axis, keep_attrs, **kwargs)
   1592         return self._replace_maybe_drop_dims(var)
   1593 

~/anaconda3/lib/python3.7/site-packages/xarray/core/variable.py in reduce(self, func, dim, axis, keep_attrs, allow_lazy, **kwargs)
   1338 
   1339         if dim is not None:
-> 1340             axis = self.get_axis_num(dim)
   1341         data = func(self.data if allow_lazy else self.values,
   1342                     axis=axis, **kwargs)

~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in get_axis_num(self, dim)
    128         """
    129         if isinstance(dim, basestring):
--> 130             return self._get_axis_num(dim)
    131         else:
    132             return tuple(self._get_axis_num(d) for d in dim)

~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in _get_axis_num(self, dim)
    137         except ValueError:
    138             raise ValueError("%r not found in array dimensions %r" %
--> 139                              (dim, self.dims))
    140 
    141     @property

ValueError: 'lon' not found in array dimensions ('mid_levels', 'latitude', 'longitude')

**Comment by JoyMonteiro** [comment]
I have just released a new version of climt. It has both python 3.6 and 3.7 support. You should be able to just `pip install -U climt` on your py37 distribution.

let me know if you are able to succesfully install it and run the above notebook. That notebook would not run on the older version of climt (0.15.3) since I have changed names of the dimensions since then. They were previously `latitude, longitude`, and now they are `lat, lon`.

**Comment by musdfakoc** [comment]
nope it still gives the same errors as before.
and I am sending you the plot that I get when I run the baroclinic_wave.py in examples
![screen shot 2018-10-09 at 22 41 03](https://user-images.githubusercontent.com/43886706/46694160-9837b500-cc14-11e8-8d3d-a8c89e6d0752.png)
this stays like that forever.

**Comment by JoyMonteiro** [comment]
This output looks fine. You will have to clarify what you mean by

> this stays like that forever
do you mean it crashes?

> nope it still gives the same errors as before.
you have mentioned many different kinds of errors before.

**Comment by JoyMonteiro** [comment]
From here it looks like climt is working fine if that baroclinic wave example is running. I'm not sure if the problems you are facing are related to climt.

**Comment by musdfakoc** [comment]
no normally this plot is dynamic and changing always.
the error is the same for the test code you sent me HS_Test.ipynb.zip.
notebook and python is giving me 

 /Users/mustafakoc/anaconda3/lib/python3.7/site-packages/sympl/_core/tracers.py:202: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use arr[tuple(seq)] instead of arr[seq]. In the future this will be interpreted as an array index, arr[np.array(seq)], which will result either in an error or a different result.
array[tracer_slice] = raw_state[name]
max. zonal wind: 4.023865123812444
/Users/mustafakoc/anaconda3/lib/python3.7/site-packages/sympl/_core/tracers.py:229: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use arr[tuple(seq)] instead of arr[seq]. In the future this will be interpreted as an array index, arr[np.array(seq)], which will result either in an error or a different result.
raw_state[name] = tracer_array[tracer_slice]
ValueError Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in _get_axis_num(self, dim)
135 try:
--> 136 return self.dims.index(dim)
137 except ValueError:

ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

ValueError Traceback (most recent call last)
in ()
41 my_state['time'].minute == 0):
42 print('max. zonal wind: ', np.amax(my_state['eastward_wind'].values))
---> 43 monitor.store(my_state)
44 my_state.update(output)
45 my_state['time'] += model_time_step

~/anaconda3/lib/python3.7/site-packages/sympl/_components/plot.py in store(self, state)
68 fig = plt.figure()
69
---> 70 self._plot_function(fig, copy_state(state))
71
72 fig.canvas.draw()

in plot_function(fig, state)
13
14 ax = fig.add_subplot(1, 2, 1)
---> 15 state['air_temperature'].mean(dim='lon').plot.contourf(
16 ax=ax, levels=16)
17 ax.set_title('Temperature')

~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in wrapped_func(self, dim, axis, skipna, keep_attrs, **kwargs)
21 keep_attrs=False, **kwargs):
22 return self.reduce(func, dim, axis, keep_attrs=keep_attrs,
---> 23 skipna=skipna, allow_lazy=True, **kwargs)
24 else:
25 def wrapped_func(self, dim=None, axis=None, keep_attrs=False,

~/anaconda3/lib/python3.7/site-packages/xarray/core/dataarray.py in reduce(self, func, dim, axis, keep_attrs, **kwargs)
1589 summarized data and the indicated dimension(s) removed.
1590 """
-> 1591 var = self.variable.reduce(func, dim, axis, keep_attrs, **kwargs)
1592 return self._replace_maybe_drop_dims(var)
1593

~/anaconda3/lib/python3.7/site-packages/xarray/core/variable.py in reduce(self, func, dim, axis, keep_attrs, allow_lazy, **kwargs)
1338
1339 if dim is not None:
-> 1340 axis = self.get_axis_num(dim)
1341 data = func(self.data if allow_lazy else self.values,
1342 axis=axis, **kwargs)

~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in get_axis_num(self, dim)
128 """
129 if isinstance(dim, basestring):
--> 130 return self._get_axis_num(dim)
131 else:
132 return tuple(self._get_axis_num(d) for d in dim)

~/anaconda3/lib/python3.7/site-packages/xarray/core/common.py in _get_axis_num(self, dim)
137 except ValueError:
138 raise ValueError("%r not found in array dimensions %r" %
--> 139 (dim, self.dims))
140
141 @Property

ValueError: 'lon' not found in array dimensions ('mid_levels', 'latitude', 'longitude')

**Comment by musdfakoc** [comment]
no I guess the problem is with matplotlib as you mentioned before

**Comment by JoyMonteiro** [comment]
> ValueError: 'lon' not found in array dimensions ('mid_levels', 'latitude', 'longitude')

This error means that climt has not been updated to the latest version. in the new version of climt, array dimensions has changed to `('mid_levels', 'lat', 'lon')`. You should try deleting the older version.
You can find out where it is installed by running
```python
    import climt
    print(climt.__file__)
```

**Comment by musdfakoc** [comment]
ok I erased that and It worked perfectly.

**Comment by JoyMonteiro** [comment]
Good to know it is working! Please open a new issue if you anything else shows up. Glad to help!

**Comment by musdfakoc** [comment]
I have a problem with climt again in jupyter notebook, the example "column_code_with_slab.py" does not work 

NameError                                 Traceback (most recent call last)
<ipython-input-3-ec9d5dd42d20> in <module>()
     68 timestep = timedelta(minutes=10)
     69 
---> 70 convection = EmanuelConvection()
     71 radiation_sw = RRTMGShortwave()
     72 radiation_lw = RRTMGLongwave()

~/climt-develop/climt/_components/emanuel/component.py in __init__(self, minimum_convecting_layer, autoconversion_water_content_threshold, autoconversion_temperature_threshold, entrainment_mixing_coefficient, downdraft_area_fraction, precipitation_fraction_outside_cloud, speed_water_droplets, speed_snow, rain_evaporation_coefficient, snow_evaporation_coefficient, convective_momentum_transfer_coefficient, downdraft_surface_velocity_coefficient, convection_bouyancy_threshold, mass_flux_relaxation_rate, mass_flux_damping_rate, reference_mass_flux_timescale, **kwargs)
    213         self._mf_timescale = reference_mass_flux_timescale
    214         self._ntracers = 0
--> 215         self._set_fortran_constants()
    216         super(EmanuelConvection, self).__init__(**kwargs)
    217 

~/climt-develop/climt/_components/emanuel/component.py in _set_fortran_constants(self)
    225         self._rho_condensible = get_constant('density_of_liquid_phase', 'kg/m^3')
    226         self._Cl = get_constant('specific_enthalpy_of_vapor_phase', 'J/kg')
--> 227         _emanuel_convection.init_emanuel_convection(
    228             self._min_conv_layer,
    229             self._crit_humidity,

NameError: name '_emanuel_convection' is not defined

It gives this and plot is not opening.

**Comment by JoyMonteiro** [comment]
I suggest you open a new issue for further problems you face, since this one does not seem to have anything to do with climt installation on Mac OSX.

I see that this is a develop build and not an installed (binary) version. This issue is because
climt has not been compiled correctly. I'm surprised that you did not see any warnings -- the
following code should have produced a warning
https://github.com/CliMT/climt/blob/0e3877c082e05555c74cb2392efd5b7c5021f9f1/climt/_components/emanuel/component.py#L7-L14

Please check if there was an error while building climt, and report it in a separate issue.
