### ISSUE TITLE
Upon install, CLIMT breaks scipy, skimage

### ISSUE THREAD

**Issue by myak555** [CliMT/climt#96]
* CliMT version:
* Python version:
* Operating System:

### Description

Installed CLiMT normally with 
>>> pip install climt

Basically, a normal install rendered the entire Python 3.6 installation unusable. 

### What I Did

Upon the install,
>>> import skimage 
fails with message:
"ImportError: DLL load failed: The specified module could not be found."

>>> from scipy.integrate import odeint
fails with message:
"ImportError: DLL load failed: The specified module could not be found."

>>> pip install skimage 
fails with message:
"Command "python setup.py egg_info" failed with error code 1 in pip-install-gx5vglzj\skimage\

>>> pip uninstall climt
fails with message 
PermissionError: [WinError 5] Access is denied: \\AppData\\Local\\Temp\\pip-uninstall-4f54b2_l\\prog
ram files\\python36\\lib\\site-packages\\climt\\_components\\emanuel\\_emanuel_convection.cp36-win_amd64.pyd'

Windows 10 shows that my account is the owner and has full control, but the contents of /site-packages/climt and  /site-packages/climt-0.16.0.dist-info have some weird permissions and are not accessible.

To fix the bug the author must:
(1 ) As very minimum, state in the instructions that the current installation fails on Windows-10 and RENDERS SYSTEM IN UNUSABLE STATE --- DO NOT INSTALL ---
(2) Ideally provide clear instructions for Windows 10 installation

**Comment by mcgibbon** [comment]
I also have climt installed on Windows 10 without issues. This sounds like a problem particular to your installation. I can't imagine how climt might render these other packages unusable, given those other packages don't depend on climt. As for not being able to uninstall climt, you may have installed the package with administrator privileges. Could you try uninstalling from an administrator console? You can do this by right clicking the Anaconda Console shortcut and selecting "Run as administrator".

Whenever you install a package without using virtual environments, you run the risk of ruining your installation. I personally don't bother with virtual environments, but I don't mind having to re-install everything if I run into issues.

If you find a way to reproduce your issue with a fresh installation, I could try to replicate it.

**Comment by JoyMonteiro** [comment]
closing this for now.
